config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "splash_screen#index"

  resources :users, only: %i[show]

  resources :categories, only: %i[index show new create] do
    resources :expenses, only: %i[new create show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses, foreign_key: :category_id, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user, foreign_key: :author_id
  has_and_belongs_to_many :categories

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :expenses, foreign_key: :author_id, dependent: :destroy
  has_many :categories, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show]
  before_action :set_user, only: %i[index show create]

  def index
    @categories = @user.categories.includes(:expenses)
    @expenses = @categories.flat_map { |category| category.expenses.to_a }
    @expenses = @expenses.select { |expense| expense.author_id == current_user.id }
  end

  def show
    @expenses = @category.expenses.where(author_id: current_user.id).order(created_at: :desc)
    @total = @expenses.sum(&:amount)
  end

  def new
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category = @user.categories.build(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def set_category
    @category = Category.find_by(id: params[:id])
  end

  def set_user
    @user = current_user
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_user, only: %i[new create]
  before_action :set_category, only: %i[new create]

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.author_id = current_user.id
    @category.expenses << @expense

    if @expense.save!
      redirect_to category_path(@category)
    else
      render :new, alert: 'Something went wrong'
    end
  end

  private

  def set_category
    @category = @user.categories.find(params[:category_id])
  end

  def set_user
    @user = current_user
  end

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/views/categories/index.html.erb
<article class="relative w-full h-full">
  <header class="flex items-center justify-between w-full gap-2 text-sm text-center p-4 bg-sky-600 text-white h-14">
    <a href="<%=root_path%>" class="flex items-center gap-1 md:hover:grayscale md:transition">
    <%= image_tag 'mini-logo.png', class: 'w-6' %>
    </a>
    <h1 class="text-lg tracking-wider text-white uppercase pointer-events-none">Categories</h1>
    <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: 'p-1 text-white uppercase text-xs font-bold py-1.5 text-center block bg-red-600 rounded-md md:hover:bg-black md:transition' %>
  </header>
  <div class=" overflow-auto max-h-[650px] sm:rounded-b-2xl h-full">
    <ul class="relative flex flex-col gap-3 p-0 py-3 list-none">
    <% @categories.each do |category| %>
      <li class="bg-white md:hover:shadow-xl md:hover:-translate-y-1 md:active:scale-95 md:transition">
        <a href="<%= category_path(category.id) %>" class="flex items-center gap-2 p-2 px-4">
          <picture class="w-10 h-10">
            <img src="<%= category.icon %>" alt="icon" class="object-cover border rounded-md">
          </picture>
          <h2 class="text-sm truncate text-ellipsis max-w-[10rem] font-normal"><%= category.name %></h2>
          <p class="ml-auto text-lg font-bold"><%= number_to_currency((category.expenses.sum(&:amount)), precision: 2) %></p>
        </a>
      </li>
    <% end %>
    </ul>
  </div>
  <div class="mt-auto bottom-5">
     <%= link_to 'Add a New Category', new_category_path , class: 'bg-lime-500 text-white md:active:scale-95 md:hover:-translate-y-1 md:hover:shadow-xl md:transition p-2 text-black uppercase text-sm font-bold py-3 text-center block' %>
  </div>
</article>

app/views/categories/new.html.erb
<article class="w-full h-full">
  <header class="flex items-center w-full gap-2 text-sm text-center p-4 bg-sky-600 text-white h-14">
    <a href="<%= categories_path %>" class="flex items-center gap-1">
      <i class="text-white text-md fa-solid fa-arrow-left"></i>
    </a>
    <h1 class="text-sm font-normal tracking-wider text-white uppercase pointer-events-none pl-20">New Category</h1>
  </header>
  <div>
    <%= form_for @category, url: categories_path, method: :post do |f| %>
      <fieldset>
         <%= f.text_field :name, id: 'category_name', autofocus: true, autocomplete: "name", placeholder: 'Name', class:'w-full border-x-transparent border-y  border-t-2   border-gray-200 outline-1 focus:border-transparent focus:ring-0', required: true %>
      </fieldset>
      <fieldset>
          <%= f.text_field :icon, id: 'category_icon', autofocus: true, autocomplete: "icon", placeholder: 'Icon (URL)', class:'w-full border-x-transparent border-y  border-t-2 border-gray-200 outline-1 focus:border-transparent focus:ring-0', required: true %>
      </fieldset>
      <fieldset class="mt-5 text-center actions">
        <%= f.submit "Save", class: "bg-sky-600 p-2 text-sm w-full block text-white md:hover:bg-black md:hover:text-white md:transition tracking-wide text-center cursor-pointer" %>
      </fieldset>
    <% end %>
  </div>
</article>

app/views/categories/show.html.erb
<article class="relative w-full h-full bg-gray-100 sm:rounded-2xl">
  <header class="flex items-center w-full gap-2 text-sm text-center p-4 bg-sky-600 text-white h-14">
    <a href="<%= categories_path %>" class="flex items-center gap-1">
      <i class="text-white text-md fa-solid fa-arrow-left"></i>
    </a>
    <h2 class="text-center text-l tracking-wider text-white uppercase pointer-events-none pl-20">TRANSACTIONS</h2>
  </header>
  <div class="h-full overflow-auto max-h-[650px]">
    <header class="my-3 bg-white md:transition">
      <div class="flex items-center gap-2 px-4 py-3">
        <picture class="w-12 h-12">
          <img src="<%= @category.icon %>" alt="icon" class="object-cover border rounded-md">
        </picture>
        <h3 class="text-base truncate text-ellipsis max-w-[10rem] font-normal"><%= @category.name %></h2>
        <p class="ml-auto text-2xl font-bold"><%= number_to_currency(@total, precision: 2) %></p>
      </div>
    </header>
    <ul class="relative flex flex-col gap-3 p-0 py-3 list-none">
    <% if @expenses %>
      <% @expenses.each do |expense| %>
        <li class="bg-white md:hover:shadow-xl md:hover:-translate-y-1 md:active:scale-95 md:transition">
          <a href="<%= category_expense_path(expense.id) %>" class="flex items-center gap-2 p-2 px-4">
            <h4 class="text-sm truncate text-ellipsis max-w-[10rem] font-normal"><%= expense.name %></h2>
            <p class="ml-auto text-lg font-bold"><%= number_to_currency(expense.amount, precision: 2) %></p>
          </a>
        </li>
      <% end %>
    <% end %>
    </ul>
  </div>
  <div class="mt-auto bottom-8">
    <%= link_to 'Add a New Transaction', new_category_expense_path(@category) , class: 'bg-lime-500 md:active:scale-95 md:hover:-translate-y-1 md:hover:shadow-xl md:transition p-2 text-white uppercase text-sm font-bold py-3 text-center block'%>
  </div>
</article>

app/views/expenses/new.html.erb
<article class="w-full h-full bg-gray-100 sm:rounded-2xl">
  <header class="flex items-center w-full gap-2 text-sm text-center p-4 bg-sky-600 text-white h-14">
    <a href="<%= category_path(@category) %>" class="flex items-center gap-1">
      <i class="text-white text-md fa-solid fa-arrow-left"></i>
    </a>
    <h1 class="text-sm font-normal tracking-wider text-white uppercase pointer-events-none pl-20 ">New Transaction</h1>
  </header>
  <div>
    <%= form_for :expense, url: category_expenses_path(@category), method: :post do |f| %>
      <fieldset>
         <%= f.text_field :name, id: 'name', autofocus: true, autocomplete: "name", placeholder: 'Name', class:'w-full border-x-transparent border-y  border-t-2   border-gray-200 outline-1 focus:border-transparent focus:ring-0', required: true %>
      </fieldset>
      <fieldset>
          <%= f.text_field :amount, id: 'amount', autofocus: true, autocomplete: "amount", placeholder: 'Amount', class:'w-full border-x-transparent border-y  border-t-2 border-gray-200 outline-1 focus:border-transparent focus:ring-0', required: true %>
      </fieldset>
      <fieldset class="mt-5 text-center actions">
        <%= f.submit "Save", class: "bg-sky-600 p-2 text-sm w-full block text-white md:hover:bg-black md:hover:text-white md:transition tracking-wide text-center cursor-pointer" %>
      </fieldset>
    <% end %>
  </div>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'mini-logo.png' %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main class="container mx-auto mt-28 px-5 flex sm:max-w-sm h-screen bg-gray-100 font-sans">
      <%= yield %>
    </main>
  </body>
</html>

app/views/splash_screen/index.html.erb
<article class='relative flex items-center w-full h-full p-2'>
  <div class="flex items-center justify-center w-full gap-2 mb-5 text-center">
    <%= image_tag 'logo.PNG', class:'w-6/12' %>
  </div>
  <div class="absolute left-0 grid w-full px-2 gap-2 text-sm bottom-20">
    <%= link_to 'Login', new_user_session_path, class:'text-white bg-sky-600 block w-full p-2 py-4 tracking-wide uppercase md:hover:bg-black md:hover:text-white md:transition text-center' %>
    <%= link_to 'Sign Up', new_user_registration_path, class: ' text-white bg-sky-600 block w-full p-2 py-4 tracking-wide uppercase md:hover:bg-black md:hover:text-white md:transition text-center' %>
  </div>
</article>